name: Maven Builder for Spigot Plugin
author: "JIN-InI"
description: "Maven builder for Spigot/Paper plugins"
branding:
  icon: "settings"
  color: "orange"

on: [push, pull_request]
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          cache: 'maven'
          distribution: 'adopt'

      - name: Build with Maven and copy artifacts
        run: mvn -B package -f pom.xml && mkdir ~/artifacts && cp target/*.jar ~/artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact-jar
          path: ~/artifacts/*
